[package]
name = "rust_kernel"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "database",
    "draw_core",
    "encryption", 
    "file_storage",
    "lib_base",
    "libdump",
    "logger",
    "netlib",
    "screen_capture",
    "secure_store",
    "xtask",
]
resolver = "2"

[dependencies]

[profile.release]
lto = true
opt-level = "s"
